### ISSUE TITLE
Help sorted by Category and  Alphabetically

### ISSUE THREAD

**Issue by BannukDE** [An-Idiots-Guide/guidebot#10]
https://github.com/An-Idiots-Guide/guidebot/blob/6a5e324be2817ceca8f56470d4a4db938a67e62c/commands/help.js#L9

switch with:
````
const sorted = myCommands.sort((p, c) => p.help.category > c.help.category
  ? 1 :  p.help.name > c.help.name && p.help.category === c.help.category
    ? 1 : -1
);
````

**Comment by YorkAARGH** [comment]
I just want to start off by apologising for taking so long to respond to you, but I want to thank you for taking the time to figure this out, I've done extensive testing and found that this indeed does as described and we're inviting you to submit it as a PR where we will approve it.
