### ISSUE TITLE
Upgrade to d.js v12.

### ISSUE THREAD

**Issue by reisxd** [An-Idiots-Guide/guidebot#117]
The v11 wont work after 7 days. Please update to v12.

**Comment by eslachance** [comment]
Yeah.. not only are we aware, you probably got reminded of this **because of the announcement I made**. And also, guidebot *is* update to v12 already. If there's anything missing, please feel free to make a PR with the code changes.

**Comment by reisxd** [comment]
> Yeah.. not only are we aware, you probably got reminded of this **because of the announcement I made**. And also, guidebot _is_ update to v12 already. If there's anything missing, please feel free to make a PR with the code changes.

The dashboard one is updated or not?
