### ISSUE TITLE
error when trying to start

### ISSUE THREAD

**Issue by georgetzlp** [An-Idiots-Guide/guidebot#119]
hey, so I've got everything installed from the requirements and when I try to start the bot I get [this](https://i.imgur.com/YwQ4YfZ.png) how could I fix this?

**Comment by RavynGG** [comment]
you've got to enable privileged intent

**Comment by RavynGG** [comment]
you can enable it in discord bot settings at discord.com/developers

**Comment by thetayloredman** [comment]
@wathhr enable guild_members and member_presences on the application portal @ discord.com/developers

**Comment by eslachance** [comment]
For tech support please join https://discord.gg/4NE4bk7
