### ISSUE TITLE
How to create new settings?

### ISSUE THREAD

**Issue by Sarveshmrao** [An-Idiots-Guide/guidebot#120]
This is not an issue but a question. I want to know how I can create more settings. 

```
prefix, modLogChannel,modRole, adminRole, systemNotice, welcomeChannel, welcomeMessage, welcomeEnabled
```
These are the default settings for guilds. I want to add more settings. How can I do that? 

I tried adding those settings in `defaultSettings` in `setup.js` file. But that didn't work. 

Thanks in advance! 

PS: The Discord Invite link in the repo's `CONTRIBUTING.md` is invalid. This made me open an issue.

**Comment by eslachance** [comment]
Once the bot is up and running, you must add new settings using the `conf` command. `defaultSettings` is only used on first load, and then it's discarded unless you run the setup again. `conf`, on the other hand, modifies the default value stored in the database. Once you use `conf` to add a new value, each guild can use `set` to change it.

Thanks for the note about contributing.md, we'll fix that asap. In the meantime, the correct invite is https://discord.gg/4NE4bk7
