### ISSUE TITLE
 invalid or corrupt file : cannot read at 0x404BDD

### ISSUE THREAD

**Issue by Kurpp** [An-Idiots-Guide/guidebot#126]
I cloned the github, downloaded everything required, yet im still faced with this error code (see attachement below)

![](https://pays.host/uploads/8ecd55c5-2897-4a31-9f43-10d49a20ad08/kKhCjEY8.png)

**Comment by eslachance** [comment]
You failed to properly follow instructions in regards to pre-requisites for the bot. Please make sure to carefully follow the readme, and join us on Discord for more help. https://discord.gg/4NE4bk7
