### ISSUE TITLE
Error in setup.js

### ISSUE THREAD

**Issue by ItzFaruq** [An-Idiots-Guide/guidebot#128]
I got some error in setup.js, how to fix it?

![Screenshot_2021-03-27-16-33-05-76](https://user-images.githubusercontent.com/79438552/112716693-864c4880-8f1a-11eb-9402-170e7c64eeec.jpg)
![Screenshot_2021-03-27-16-33-13-34](https://user-images.githubusercontent.com/79438552/112716695-88160c00-8f1a-11eb-8e37-c4825019ba3d.jpg)

**Comment by kyranet** [comment]
First of all, there are no errors in either screenshot.
Second, please post errors as plain text, reading them from screenshots is extremely hard.

**Comment by Faruq15** [comment]
![Uploading Screenshot_2021-03-27-16-37-40-79.jpg…]()

**Comment by ItzFaruq** [comment]
Like this from console

![Screenshot_2021-03-27-16-37-40-79](https://user-images.githubusercontent.com/79438552/112716804-2013f580-8f1b-11eb-9a09-2e527b140581.jpg)
![Screenshot_2021-03-27-16-41-00-65](https://user-images.githubusercontent.com/79438552/112716857-6b2e0880-8f1b-11eb-8a60-ce8ad11965ae.jpg)

**Comment by ItzFaruq** [comment]
Sad, idk what happens

**Comment by kyranet** [comment]
Please update to the latest version, the issue has been resolved in the PR above.

And next time, please post your errors as plain text, not as images, each screenshot is 2 screens tall and is barely readable.

**Comment by ItzFaruq** [comment]
Ok

**Comment by ItzFaruq** [comment]
Ok

> Please update to the latest version, the issue has been resolved in the PR above.
> 
> And next time, please post your errors as plain text, not as images, each screenshot is 2 screens tall and is barely readable.

Mm but i was update it? Discord i using 12.5.1
And i use latest update from AnldiotsGuide

**Comment by kyranet** [comment]
> And i use latest update from AnldiotsGuide

I meant updating guidebot, the latest version includes a fix for your issue.
