### ISSUE TITLE
Client.loadCommand is not a function.

### ISSUE THREAD

**Issue by BrainyV** [An-Idiots-Guide/guidebot#131]
# I get this error

(node:230) UnhandledPromiseRejectionWarning: TypeError: client.loadCommand is not a function
    at /home/runner/testing/index.js:26:29
    at Array.forEach (<anonymous>)
    at init (/home/runner/testing/index.js:24:12)
(node:230) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:230) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by eslachance** [comment]
Please join the server for technical support so we can best help you. https://discord.gg/4NE4bk7
