### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KainesLaw** [An-Idiots-Guide/guidebot#138]
I got a settings suggestion, maybe make a setting to be able to hide a command from the `help` menu. I could use it to hide owner commands, again members can't use it, but it would be more tidy if we could just hide commands from the help menu, because they just kind of take up space.

**Comment by KainesLaw** [comment]
like for example, `hidden: false/true`

**Comment by YorkAARGH** [comment]
Guidebot already does this, members should only see the commands they can run, for example this is a user, and myself using the `help` command of the same bot.
[Regular user](https://i.imgur.com/6nZ3PGo.png)
[Bot owner](https://i.imgur.com/tQspVkf.png)

It actually filters out commands that are above the users level (level 0 users can't use level 10 commands for  example) [here](https://github.com/AnIdiotsGuide/guidebot/blob/master/commands/help.js#L13)

Or are you meaning _hide the command completely, regardless who runs the help command?_

**Comment by KainesLaw** [comment]
@YorkAARGH I did not know that! Thanks!
