### ISSUE TITLE
is there a way to create a new role and permission? 

### ISSUE THREAD

**Issue by KainesLaw** [An-Idiots-Guide/guidebot#140]
I want to create a `staff` role that is level 1. Right above User. I tried doing this twice and it didn't work. I tried editing the config.js file to [this](https://pastebin.com/R4Pxes6p) and it didn't work. I made a new bot, edited the config.js file to the same code, before using the conf command, and it did not work. 

Could I get some assistance to how to add a new role and permission? Thanks in advance.

**Comment by KainesLaw** [comment]
I think I figured it out.

**Comment by YorkAARGH** [comment]
You would also need to add this in the database iirc, as the code will also attempt to check for the role there.
