### ISSUE TITLE
 Node 16.x or higher is required. Update Node on your system.

### ISSUE THREAD

**Issue by ghost** [An-Idiots-Guide/guidebot#159]
I am using Replit Node and it is saying to update node, like idk about if I can do anything about it cuz Replit has to update **THEIR** node not me.

**Comment by YorkAARGH** [comment]
This is not an issue with guidebot, you would have to take it up with Repl.it or get a VPS for your bot.

**Comment by ghost** [comment]
k thx

**Comment by YorkAARGH** [comment]
Sorry we couldn't help, but discord.js itself requires node v16 or higher.

**Comment by ghost** [comment]
kk

**Comment by ghost** [comment]
Do you know where I can find the replit support, like make a ticket

**Comment by YorkAARGH** [comment]
Nope, I don't. I don't use repl.it because of this very reason, that and you can't actively use a file based database (unless they've recently changed it).

Have you tried googling "repl.it support"? Because it should be the second link in the results.

**Comment by ghost** [comment]
yeah I cant find it do you think I should just download node and just use that instead

**Comment by ghost** [comment]
> Nope, I don't. I don't use repl.it because of this very reason, that and you can't actively use a file based database (unless they've recently changed it).
> 
> Have you tried googling "repl.it support"? Because it should be the second link in the results.

can you suggest any other platform that could run the bot?

**Comment by YorkAARGH** [comment]
Literally any legitimate VPS service, not a webhost, but an actual VPS service, I won't make any recommendations because it's up to you as a consumer to do your own research on which provider you would want to use.
