### ISSUE TITLE
I finally ran the bot but it said token invalid, anyone know why?

### ISSUE THREAD

**Issue by ghost** [An-Idiots-Guide/guidebot#160]

**Comment by ghost** [comment]
yeah i just dont know

**Comment by ghost** [comment]
please help I just made the application

**Comment by WilsontheWolf** [comment]
Did you add your token to your config?

**Comment by ghost** [comment]
yeah

**Comment by WilsontheWolf** [comment]
what is your config file named?

**Comment by ghost** [comment]
config.js

**Comment by ghost** [comment]
wait where do I put the token in config?

**Comment by WilsontheWolf** [comment]
Ah sorry I just realized the token goes in the .env file. Please check if it is there.

**Comment by ghost** [comment]
yeah it is

**Comment by WilsontheWolf** [comment]
and what if your .env file name?

**Comment by ghost** [comment]
.env

**Comment by ghost** [comment]
![Web capture_19-1-2022_19224_replit com](https://user-images.githubusercontent.com/81431824/150239693-fb2ba110-8ca8-4589-b7bc-aac60490e4dc.jpeg)

**Comment by WilsontheWolf** [comment]
right before your client.login in the index.js file can you add 
```js
console.log(process.env.DISCORD_TOKEN);
``` 
then show the result

**Comment by ghost** [comment]
k

**Comment by ghost** [comment]
like client.login is line 86, do I do line 87?

**Comment by WilsontheWolf** [comment]
above the client.login would work

**Comment by ghost** [comment]
k

**Comment by kyranet** [comment]
This is GitHub, not Discord, please take chatting to https://discord.gg/vXVxsAjSMF.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/81431824/150240222-b30a563a-a84f-492d-92dd-9035b6c99745.png)

**Comment by ghost** [comment]
still invalid

**Comment by ghost** [comment]
> This is GitHub, not Discord, please take chatting to https://discord.gg/vXVxsAjSMF.

he is helping me tho

**Comment by kyranet** [comment]
I'm closing and locking this issue, this is spamming everyone's notifications (and emails). Chatting isn't something you do at GitHub, you're supposed to give meaningful messages, not streaks of "k"s.

Please take this support chat to the official server with the aforementioned link.
