### ISSUE TITLE
Not registering Slash Commands

### ISSUE THREAD

**Issue by Haaffin** [An-Idiots-Guide/guidebot#169]
Since the only other person to have this issue was rude, lemme open an actual one.

When starting the bot, it logs that the slash commands were loaded, but in the actual server nothing appears

log:
`[2023-01-08 19:19:31]: LOG Loading Slash command: leave. 👌 
[2023-01-08 19:19:31]: LOG Loading Slash command: ping. 👌 
[2023-01-08 19:19:31]: LOG Loading Slash command: stats. 👌 `

Slash Commands in the server:
<img width="722" alt="Screenshot 2023-01-08 at 7 27 45 PM" src="https://user-images.githubusercontent.com/59460574/211228855-775afe05-c1d7-4b77-8ea5-97c653f683b0.png">

**Comment by WilsontheWolf** [comment]
You need to manually deploy the commands. You should be able to do run `@bot deploy` to deploy the commands, and then they'll deploy. There is a pr open, that among other changes, documents this in the readme.
