### ISSUE TITLE
Guidebot has currency?

### ISSUE THREAD

**Issue by Excigma** [An-Idiots-Guide/guidebot#18]
![image](https://user-images.githubusercontent.com/30280397/31261058-8b71a0d4-aaae-11e7-998d-c730642f2c8e.png)

Seems here 😛 Opps.

**Comment by YorkAARGH** [comment]
@eslachance forgot to remove the cost references when she ported the new dashboard files from York-Dev.

**Comment by YorkAARGH** [comment]
This was fixed recently
