### ISSUE TITLE
Say command won't work in with command handler

### ISSUE THREAD

**Issue by antonegas** [An-Idiots-Guide/guidebot#24]
When I try to use the say command the console returns this error:
(node:10380) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Cannot send an empty message
(node:10380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

even when I writte something for the bot to copy

**Comment by YorkAARGH** [comment]
What are the steps to reproduce? Please include as much information as you
can.

**Comment by antonegas** [comment]
this is all my code excluding the config.json
const config = require("./config.json");
const Discord = require("discord.js");

const prefix = config.prefix;

const bot = new Discord.Client({disableEveryone: true});
bot.on("message", async message => {
const args = message.content.slice(prefix.length).trim().split(/ +/g);
const command = args.shift().toLowerCase();

if(command === "say"){
  let text = args.slice(1).join(" ");
  message.delete();
  message.channel.send(text);
  }}
});

bot.login(config.token);

**Comment by antonegas** [comment]
whenever I use my prefix + say <whatever>
it returns the error posted above

**Comment by YorkAARGH** [comment]
Well... for one thing, that has 100% nothing to do with this command handler / framework, and **are** you sending a message? say `<prefix>say hello world!` or are you just doing `<prefix>say` ?

**Comment by ghost** [comment]
Simplied Framework Code: 
```js
exports.run = async (client, message, args, level) => {
message.delete(1); // One interval
let text = args.join(" ")
return message.channel.send(`${text}`) //Return function
};
// Do normal things with your code
