### ISSUE TITLE
level 0 User

### ISSUE THREAD

**Issue by Nyctara** [An-Idiots-Guide/guidebot#25]
So I put my id in ownerID but when I try to use an owner command it tells me
 You do not have permission to use this command.
  Your permission level is 0 (User)
  This command requires level 10 (Bot Owner)
Any Ideas?

**Comment by YorkAARGH** [comment]
What is your user ID?

**Comment by Nyctara** [comment]
373951038157225995

**Comment by Nyctara** [comment]
are there multiple areas I need to put it in?

**Comment by YorkAARGH** [comment]
I do apologise for taking so long to respond, but looking at that ID, it does look like a valid ID, are you sure you're putting it in the correct area?

**Comment by YorkAARGH** [comment]
Closing due to no response.
