### ISSUE TITLE
?

### ISSUE THREAD

**Issue by tbnritzdoge** [An-Idiots-Guide/guidebot#42]
Whats the difference between this and https://github.com/AnIdiotsGuide/guidebot-class

**Comment by MrJacz** [comment]
Well, guidebot-class is a [**Class**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) based version of guidebot, The main difference is the use of classes of course, not sure what else to say. If you're wondering what a class is read the MDN page that I linked, Have a good day/night.
