### ISSUE TITLE
Commands not showing in help

### ISSUE THREAD

**Issue by GGrandma** [An-Idiots-Guide/guidebot#44]
I have recently noticed that some of my commands were not showing up in the help command list, I recently found out what was causing it. If you use a permissions number instead of its name, for example for a number "permLevel: 1" having it as a number makes the command not show up in help except the command still works fine... I fixed it by using the roles name, "permLevel: "User". Sorry if this is terribly explained...
P.S. I haven't tried much to fix this myself as it hasn't effected me to much.

**Comment by MrJacz** [comment]
permLevel is by level name and not number

**Comment by YorkAARGH** [comment]
Yes, this was a breaking change when we went from permission levels (what some of your commands were using) to a more user friendly approach with the permission level names, such as User, Moderator, Administrator etc

**Comment by GGrandma** [comment]
Oh, alright Thanks guys.
