### ISSUE TITLE
event.bind is not a function.

### ISSUE THREAD

**Issue by Code-Craver** [An-Idiots-Guide/guidebot#48]
hi there, i have just got your bot and i get this error in the console:
 **ERROR Unhandled rejection: TypeError: event.bind is not a function**
can anyone help.

**Comment by Code-Craver** [comment]
nevermind, fixed

**Comment by julian100004** [comment]
How did you fix it?

**Comment by eslachance** [comment]
By following the code examples properly and ensuring that all event files had a proper `module.exports` block .

**Comment by julian100004** [comment]
Oh yeah, that was the mistake. Ty.

**Comment by Fleashiu** [comment]
![giphy](https://user-images.githubusercontent.com/80263506/112338405-c7f3ae00-8ce4-11eb-950e-9f93771d277d.gif)
