### ISSUE TITLE
Individual Permission Support

### ISSUE THREAD

**Issue by bdotsamir** [An-Idiots-Guide/guidebot#49]
Hey!

So, there are the perm levels, as defined in config.js, right? What if there were perm levels that checked for individual permissions? I know this can be done with code in the command itself, but what I'm looking for is a command that will run based on if they have a certain permission as defined in the exports.conf section. I made a makeshift example that doesn't actually work.. sort of. It works in that it doesn't show up in the help command if the user doesn't have the permission defined, but it doesnt work in that the command will still be run even if the user doesn't have the permission. Here's the code:

File: `config.js`
```js
    // This level is actually a permission checking level. Use this for when you want to 
    // check if the user has a certain permission
    { level: 1,
      name: `Permission Check`,
      check: (message, cmd) => {
        try {
          if(message.member.permissions.has(cmd.conf.requires)) return true;
        } catch (e) {
          return false;
        }
      }
    },
```
File: `addemote.js`
```js
module.exports.run = (client, message, args) => {
  var emojiName = args[0];
  var emojiURL = args[1];

  if (!emojiName) return message.channel.send(`:x: You forgot the emoji name!`);
  if (!emojiURL) return message.channel.send(`:x: You forgot the emoji url!`);

  message.guild.createEmoji(emojiURL, emojiName, null, `${message.author.tag} created emoji ${emojiName}`)
    .then(emote => {
      message.channel.send(`:white_check_mark: Emote **\`${emote.name}\`** ${emote} created!`);
    })
    .catch((err) => {message.channel.send(`:x: Something went wrong:\n${err}`);});
};

exports.conf = {
  enabled: true,
  guildOnly: true,
  aliases: [`ae`, `addemoji`, `createemoji`, `createemote`],
  permLevel: `Permission Check`,
  requires: `MANAGE_EMOJIS`
};

exports.help = {
  name: `addemote`,
  description: `Adds an emoji to the server`,
  usage: `addemote <name> <url>`,
  category: `Server`
};
```

**Comment by eslachance** [comment]
You'll have to modify the `./events/message.js` and `./modules/functions.js` in order to account for the changes in your permission procedure. At the moment, the perm check only considers the message and everything available from the message itself. If you want to add a custom argument to the perm check, you need to edit both those files accordingly.

**Comment by eslachance** [comment]
For future support, please join the Idiot's Guide guild, as the issues on github are meant to report issues with the code, not request for assistance in programming your own bot.
