### ISSUE TITLE
it cannot find discord.js

### ISSUE THREAD

**Issue by r58iiz** [An-Idiots-Guide/guidebot#51]
![eroor](https://user-images.githubusercontent.com/39996926/44847751-067e7480-ac72-11e8-870e-7ab2c4fa0deb.png)
Error picture above

**Comment by kyranet** [comment]
You have to install discord.js:

```
npm i discord.js
```

Or if you use yarn:

```
yarn add discord.js
```

**Comment by r58iiz** [comment]
I did that before when I saw that error but what I meant was that you  could include it in the package for the people who don’t bother to install or pay attention. ***This Does Not Work On Zeit.co  When Ever I Try To Upload To Server It Gives Me A Really Long Error. Please check. (The website is Https://zeit.co)***

**Comment by eslachance** [comment]
We cannot support every random host out there. If zeit.co breaks guidebot, you`ll need to talk to their support, this is not related to our code or work.
