### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by Ased2235** [An-Idiots-Guide/guidebot#53]
When i do `npm install` this error came up
`> integer@1.0.5 install C:\Mybot\guidebot\guidebot\node_modu
les\integer`
> node-gyp rebuild
C:\Mybot\guidebot\guidebot\node_modules\integer>if not defin
ed npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modu
les\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" reb
uild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-g
yp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python37\python.EXE -c im
port platform; print(platform.python_version());
gyp ERR! stack Traceback (most recent call last):
gyp ERR! stack   File "<string>", line 1, in <module>
gyp ERR! stack   File "E:\Program Files\Python36-32\Lib\platform.py", line 116,
in <module
gyp ERR! stack     import sys, os, re, subprocess
gyp ERR! stack   File "E:\Program Files\Python36-32\Lib\re.py", line 123, in <mo
dule
gyp ERR! stack     import sre_compile
gyp ERR! stack   File "E:\Program Files\Python36-32\Lib\sre_compile.py", line 17
, in module
gyp ERR! stack     assert _sre.MAGIC == MAGIC, "SRE module mismatch"
gyp ERR! stack AssertionError: SRE module mismatch
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Mybot\guidebot\guidebot\node_modules\integer
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is inst
alled. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but non
e is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is insta
lled. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is inst
alled. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installe
d. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none
 is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed.
You must install peer dependencies yourself.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2018-09-03T04_50_25_
243Z-debug.log

**Comment by YorkAARGH** [comment]
@eslachance do you know how to fix this?

**Comment by eslachance** [comment]
Would have to follow the install instructions from here: https://enmap.evie.codes/install#pre-requisites

There have been many issues with node-gyp, but unfortunately there's not much we can do beyond "here's the right instrutions".

**Comment by Ased2235** [comment]
@eslachance  When i do `npm i better-sqlite-pool` this error came.

`> Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>npm i better-sqlite-pool

> integer@1.0.5` install C:\Windows\system32\node_modules\integer
> node-gyp rebuild


C:\Windows\system32\node_modules\integer>if not defined npm_config_node_gyp (nod
e "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-
bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Prog
ram Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild
 )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\MJYOUSAF\.windows-build-tools\pyt
hon27\python.exe -c import platform; print(platform.python_version());
gyp ERR! stack   File "E:\Program Files\Python36-32\Lib\site.py", line 177
gyp ERR! stack     file=sys.stderr)
gyp ERR! stack         ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)

gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\integer
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\pac
kage.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MJYOUSAF\AppData\Roaming\npm-cache\_logs\2018-09-05T21_41_
33_452Z-debug.log

C:\Windows\system32>`

**Comment by eslachance** [comment]
Ok but what happens when you *actually* follow https://enmap.evie.codes/install#pre-requisites correctly, step by step, from top to bottom?

**Comment by Ased2235** [comment]
When i do `npm i enmap@latest`
 this error came up
C:\Users\I.N.A\Desktop\Mybot\guidebot>npm i enmap@latest

> integer@1.0.5 install C:\Mybot\guidebot\node_modules\integ
er
> node-gyp rebuild


C:\Mybot\guidebot\node_modules\integer>if not defined npm_co
nfig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-l
ifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  e
lse (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\no
de-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python37\python.EXE -c im
port platform; print(platform.python_version());
gyp ERR! stack Traceback (most recent call last):
gyp ERR! stack   File "<string>", line 1, in <module>
gyp ERR! stack   File "E:\Program Files\Python36-32\Lib\platform.py", line 116,
in <module>
gyp ERR! stack     import sys, os, re, subprocess
gyp ERR! stack   File "E:\Program Files\Python36-32\Lib\re.py", line 123, in <mo
dule>
gyp ERR! stack     import sre_compile
gyp ERR! stack   File "E:\Program Files\Python36-32\Lib\sre_compile.py", line 17
, in <module>
gyp ERR! stack     assert _sre.MAGIC == MAGIC, "SRE module mismatch"
gyp ERR! stack AssertionError: SRE module mismatch
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)

gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\I.N.A\Desktop\Mybot\guidebot\node_modules\integer
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.


   ?─────────────────────────────────────?
   │                                     │
   │   Update available 5.6.0 → 6.4.1    │
   │       Run npm i npm to update       │
   │                                     │
   ?─────────────────────────────────────?


npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\I.N.A\AppData\Roaming\npm-cache\_logs\2018-09-06T12_32_13_
293Z-debug.log

C:\Mybot\guidebot>

**Comment by eslachance** [comment]
You will keep getting the same problem until you follow the installation instructions I linked to. 
![image](https://user-images.githubusercontent.com/643344/45159508-ecceb700-b1b4-11e8-8f7f-d8a3c48aef06.png)

**Comment by Ased2235** [comment]
i installed that commend, i'm getting error afterword

**Comment by PaulHariel** [comment]
Same, I tried everything that I found letter by letter. Can you send a compressed file of all the node_modules please ?

**Comment by eslachance** [comment]
@JacqueSatan not possible. Modules require to be built on the operating system they will be run on.
