### ISSUE TITLE
TypeError: Cannot read property 'permLevel' of undefined

### ISSUE THREAD

**Issue by OmiMike** [An-Idiots-Guide/guidebot#62]
Not sure what the issue is but i am running the exact help.js that is from here and i am getting this error.

if anyone could help me with this please
![screenshot from 2018-10-05 23-36-15](https://user-images.githubusercontent.com/39207164/46567001-b8efca00-c8f7-11e8-9a7d-81943f5514b2.png)

**Comment by oJaqob** [comment]
I get the same error.

**Comment by eslachance** [comment]
Please join the discord server for any assistance. https://discord.gg/4NE4bk7

**Comment by oJaqob** [comment]
Lol discord.js? :joy: more like discord.gg
