### ISSUE TITLE
secret & oauth help

### ISSUE THREAD

**Issue by ghost** [An-Idiots-Guide/guidebot#63]
Hi, I tried to login to the dashboard on `localhost` and when I authorized my application for oauth (i had the local host url included in the oauth section of the app) and I received an error on the `/callback` page and when I try to manually authorize it from the developers page and login through there it says `UNKNOWN_ERROR`. Am I able to get help on this???

**Comment by YorkAARGH** [comment]
join the server for better help

**Comment by ghost** [comment]
thanks, i will do it once i get home from school
