### ISSUE TITLE
Discord Server Invite Invalid

### ISSUE THREAD

**Issue by ettolrach** [An-Idiots-Guide/guidebot#65]
It's most likely expired, but following [this link](https://discord.gg/gkZCQtH) as is shown in the guidebook and in the contributing guidelines brings you to an invalid invite.

Edit: [The link](https://discord.gg/4NE4bk7) that's at the header of the guidebook, does in fact work.

**Comment by YorkAARGH** [comment]
yeah, we were victim to bot raids so we had to invalidate all the invite links, will update them when I get chance
