### ISSUE TITLE
[PROPOSAL] Unknown command message

### ISSUE THREAD

**Issue by Horus125** [An-Idiots-Guide/guidebot#75]
I noticed there is no message when you use command that doesn't exist (or misspell one that does), and I think it should be included by default. I know how to do this and would like to contribute to this project, what do you think?

**Comment by kyranet** [comment]
That's against the point 6 in [Discord Bot Best Practises](https://github.com/meew0/discord-bot-best-practices)

**Comment by Horus125** [comment]
On the other hand it also says:
> If your bot's prefix is configurable, this rule can probably be safely disregarded

And you can change the prefix in the config file, or am I missing something?

**Comment by YorkAARGH** [comment]
A lot of bot listing services will punish bot authors if they have a "command not found" response, and a lot of people do use guidebot as a base so adding this to the guideline proposed by meew, regardless of the configurable prefix (the bot should respond with the prefix on mention) so we will not be adding a "command not found" response.

**Comment by eslachance** [comment]
We've decided as a team that we would not have unknown command messages in guidebot, first from the perspective of those Best Practices, and also by personal choice because we simply don't like that. You're free to add it on your own bot though!
