### ISSUE TITLE
Is there a way to have 2 message listeners

### ISSUE THREAD

**Issue by Kongolan** [An-Idiots-Guide/guidebot#79]
I'm running a webhook and bot merged together, so only passing commands with prefix through the message listener is not the best option for. Editing the message.js is not the best way to achieve those different type of listeners, so the optimal way would be to have 2 message.js, one for the webhook and one for the commands with prefix.

Is there any way to do this, with the module setup?

**Comment by eslachance** [comment]
I don't know why you'd think using message.js would be the wrong way to do it - that's precisely what message.js is meant to be used for - receiving *all* the messages. Guidebot doesn't have the capacity to load 2 different message events, but you could just add your own `client.on("messages"` in the main file if that's what you want.

**Comment by Kongolan** [comment]
Yes, i figured that too. Just old conventions for me to have very different checks and functionality not in the same file with ifs. But yes i figured I could just call client.on once again, dirty way still, but what else should i do. Thanks for the reply. Can be closed.
