### ISSUE TITLE
set command empty value

### ISSUE THREAD

**Issue by BannukDE** [An-Idiots-Guide/guidebot#8]
In line 24 of set.js:
if (!value) seems to be always false as u can parse "nothing".
After parsing "nothing" you can not change it back via "set edit key value" as the empty key can not be found by: if (!settings[key])

My solution for now:
if (!value && value == "")

**Comment by YorkAARGH** [comment]
Thank you for bringing that to our attention, I will do some testing and
debugging after I have cleaned my PC, unless evie beats me to it.

**Comment by eslachance** [comment]
You're correct that the condition doesn't work, but wrong about the reason. `value` being an *array*, an empty array is truthey, not falsey, so that's the issue.

Will fix.
