### ISSUE TITLE
Error cannot read property (default is always undefined)

### ISSUE THREAD

**Issue by Bonnaduce** [An-Idiots-Guide/guidebot#81]
![imagen](https://user-images.githubusercontent.com/47038486/56297193-866c2880-60f5-11e9-9c54-54551575eeb4.png)

Always i get some error when i try to interact with my bot, i haven't change a thing of the code apart from this one:
events/message.js
                     const settings = client.config.defaultSettings;
because withput that change i can't get the bot responde a thing :(

**Comment by Bonnaduce** [comment]
It seems that it isnt initialized the enmap "settings" for some reason, im still digging

**Comment by lukeacat** [comment]
same issue!

**Comment by AndrewJWin** [comment]
This issue hasn't been noticed/worked on for over 40 days.. If you two are still having the same issue, please bring this issue to the Idiot's Guide guild.

**Comment by eslachance** [comment]
Fixed in latest version, please ensure that you're updating all dependencies (enmap 5.0 is now being used)
