### ISSUE TITLE
How to grab mentioned user's level?

### ISSUE THREAD

**Issue by Swordington** [An-Idiots-Guide/guidebot#82]
Hi there! How do I fetch/grab a mentioned / otherwise selected (other than the message author) user's level? I'm trying to make a dynamic whois command that shows something different for level 8,9,10 users.
Any help is greatly appreciated! Thanks!

**Comment by AndrewJWin** [comment]
This question is more suited for the Idiot's Guide discord. However, an answer to your question be found [here](https://github.com/AnIdiotsGuide/guidebot/blob/0809a0019ced8ceb306407c402b133fe53168240/modules/functions.js#L12).

**Recommend closing**

**Comment by YorkAARGH** [comment]
You can access the mentioned users perm level by grabbing the member object first by `message.mentions.users.first()` then it's just a simple `user.permLevel` and you have their level. but as @AndrewJWin has mentioned these kind of questions belong on the Idiot's Guide support guild, here's an invite.

https://discord.gg/4NE4bk7
