### ISSUE TITLE
Handle eval output longer than 2000 characters

### ISSUE THREAD

**Issue by JacenBoy** [An-Idiots-Guide/guidebot#92]
Currently if the output of the eval command is greater than the Discord message limit, the command errors and does not send any kind of message. If the output of the eval command is longer than the Discord message limit, the output should be logged elsewhere (maybe to console?) and a message should be sent letting the user know.

**Comment by psibean** [comment]
Wouldn't providing a paginated response, or breaking up the output into multiple replies also work?

**Comment by YorkAARGH** [comment]
> Wouldn't providing a paginated response, or breaking up the output into multiple replies also work?

For a simple boilerplate bot to get you started within the world of bot development?
Do you realise how much work that would be, and how painful it would also be to keep user friendly and well documented?

Since the author of the issue closed their PR, I will be closing this issue.
